### ISSUE TITLE
Updating "universal-user-agent" dependency package to version 7.0.0 

### ISSUE THREAD

**Issue by TemRhythm** [octokit/request.js#449] opened 2022-01-31 13:29 UTC
It's needed to use request on latest macOS Monterey 12

**Comment by wolfy1339** [comment] 2022-01-31 14:26
That is not possible at this time. `v7` of `universal-user-agent` switches to ESM.

Unfortunately the JS octokit libraries no longer have an active maintainer.

You can read about it in [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), subscribe to it for further updates.

**Comment by daniel-beard** [comment] 2022-03-01 23:31
Are there any known workarounds for this? I guess I can just fork and republish?

**Comment by wolfy1339** [comment] 2022-03-02 03:13
Is there any kind of error message, or some message in the console?
It would help me figure out what exactly is going on.

Otherwise, I simply do not see any relevant change in between the versions. Only that the package moved to pure ESM.

**Comment by wolfy1339** [comment] 2022-05-15 16:11
@TemRhythm @daniel-beard Is this issue still relevant?

If so, can you please respond to the questions I asked in my previous comment

**Comment by wolfy1339** [comment] 2022-07-11 00:15
@octokit/js-community Is anynyone able to test this?

**Comment by gr2m** [comment] 2022-07-12 21:01
> It's needed to use request on latest macOS Monterey 12

I have MacOS Montery 12 and `@octokit/request` works just fine for me. We'd need a reproducible test case

**Comment by wolfy1339** [comment] 2023-07-11 21:23
Closing as we cannot reproduce this issue, and no update for almost a year

**Closed by wolfy1339** 2023-07-11 21:23 UTC
Labels: Status: Needs info, Type: Maintenance
