### ISSUE TITLE
[BUG]: Started facing Could not find a declaration file for module '@octokit/request' from yesterday Onwards

### ISSUE THREAD

**Issue by anshulgargamway** [octokit/request.js#585] opened 2023-05-17 05:10 UTC
### What happened?

I think this issue is linked to new version published for `@octokit/request` 

We started facing this issue from few hours onwards after release of `v6.2.4`. Any help over here will be great.

`
/../node_modules/@octokit/core/dist-types/index.d.ts(2,25): error TS7016: Could not find a declaration file for module '@octokit/request'. '/<path>/node_modules/@octokit/request/dist-node/index.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/octokit__request` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/request';`
`

### Versions

v6.2.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aj84276** [comment] 2023-05-17 05:37
we are facing

**Comment by wolfy1339** [comment] 2023-05-17 10:14
Duplicate of #583

**Closed** 2023-05-17 10:15 UTC
Labels: Duplicate
